version: '3'

services:
  postgreDB:
     image: postgres:11.1
     restart: always
     environment:
         POSTGRES_USER: testuser
         POSTGRES_PASSWORD: testpwd
         POSTGRES_DB: testdb
     volumes:
       - pgdata:/var/lib/postgresql/data
       - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
  consoleapp:
    image: consoleapp
    restart: 'no'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - 5000:80
    depends_on:
       - "postgreDB"

volumes:
  pgdata: