version: '3'

services:
  postgreDB:
     image: postgres:11.1
     restart: always
     environment:
         POSTGRES_USER: test
         POSTGRES_PASSWORD: test
         POSTGRES_DB: testdb
     volumes:
       - ./Database/scripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
       - pgdata:/var/lib/postgresql/data
     ports:
       - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 8080:80
    links:
        - "postgreDB:pgsql-server"     
    volumes:
        - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data: